# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "8732374nsddhg3223gg23dsds"
    dynamodb_table = "sdsn338787sdksbkdsdsnds"
    encrypt        = true
    key            = "tofu.tfstate"
    region         = "us-east-1"
  }
}
